sudo: required
services:
  - docker

before_install:
  - docker build -t chenglabs/docker-react -f Dockerfile.dev .

script:
  - docker run chenglabs/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-914469137639"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  
